version : '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/restaurant_v2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: springstudent
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db


  db:
    image : mysql:8.0
    container_name: my_mysql
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: springstudent
      MYSQL_DATABASE: restaurant_v2

    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql